templates:
  torrent:
    transmission:
      host: localhost
      port: 9091
      username: transmission
      password: raspberry
    clean_transmission:
      host: localhost
      port: 9091
      username: transmission
      password: raspberry
      finished_for: 6 hours
      min_ratio: 2

tasks:
  tv_show:
    rss: http://some-rss-feed.com
    series:
      - Some Series Name
    template: torrent

schedules:
  - tasks: tv_show
    interval:
      hours: 1
